Repository githubschool/mint, pull requests merged in 2020-11, with the labels that each got.

#15 update caption to reflect image
  _slides/04-OhReallyOwl.md
Labels: caption-revisions

#11 update caption to VS CODE!
  _slides/05-PN-Washington.md
Labels: VS CODE

#14 modified readme.md
  _slides/06-ccolaso.md
Labels: caption
